version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'

  backend:
    build: ./backend
    ports:
      - '8080:8080'

  telegram-bot:
    build: ./telegram-bot
    ports:
      - '8000:8000'
